name:                slick
version:             0.2.0.0
github:              "ChrisPenner/slick"
license:             BSD3
author:              "Chris Penner"
maintainer:          "example@example.com"
copyright:           "2018 Chris Penner"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ChrisPenner/slick#readme>

dependencies:
- base >= 4.7 && < 5
- shake
- aeson
- lens-aeson
- lens
- pandoc
- text
- binary
- bytestring
- containers
- mustache
- time

library:
  source-dirs: src

tests:
  slick-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - slick
