name:                slick
version:             0.1.0.0
github:              "migamake/slicker"
license:             BSD3
author:              "Chris Penner, Michał J. Gajda, Sergey Bushnyak"
maintainer:          "example@example.com"
copyright:           "2018, Chris Penner, 2019, Michał J. Gajda, Sergey Bushnyak"
extra-source-files:
- README.md
- ChangeLog.md
description:         Please see the README on GitHub at <https://github.com/migamake/slicker#readme>
dependencies:
- base >= 4.7 && < 5
- shake
- aeson
- lens-aeson
- lens
- pandoc
- text
- binary
- bytestring
- containers
- mustache
- time

library:
  source-dirs: src

tests:
  slick-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - slick
